// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_legend_wizard = "CgkI2qaGpcwREAIQBQ"; // <GPGSID>
        public const string leaderboard_best_score = "CgkI2qaGpcwREAIQAQ"; // <GPGSID>
        public const string achievement_learner = "CgkI2qaGpcwREAIQBw"; // <GPGSID>
        public const string achievement_godlike = "CgkI2qaGpcwREAIQDA"; // <GPGSID>
        public const string achievement_master_wizard = "CgkI2qaGpcwREAIQBA"; // <GPGSID>
        public const string achievement_experienced = "CgkI2qaGpcwREAIQCQ"; // <GPGSID>
        public const string achievement_professional = "CgkI2qaGpcwREAIQCw"; // <GPGSID>
        public const string achievement_skilled = "CgkI2qaGpcwREAIQCg"; // <GPGSID>
        public const string achievement_expert_wizard = "CgkI2qaGpcwREAIQAw"; // <GPGSID>
        public const string achievement_beginner_wizard = "CgkI2qaGpcwREAIQAg"; // <GPGSID>
        public const string achievement_noob = "CgkI2qaGpcwREAIQBg"; // <GPGSID>
        public const string achievement_untrained = "CgkI2qaGpcwREAIQCA"; // <GPGSID>

}

